Azure-Samples/active-directory-dotnet-iwa-v2

AppCreationScripts/sample.json, README.md
* ...
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Minor fixes

AppCreationScripts/AppCreationScripts.md, AppCreationScripts/Cleanup.ps1, AppCreationScripts/Configure.ps1, AppCreationScripts/apps.json, README.md, iwa-console/Program.cs
Updated readme, added automation
```
[ ] Yes
[ X] No
```
```
[ ] Bugfix
[ ] Feature
[ X] Code style update (formatting, local variables)
[ X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Another round of enhancements

AppCreationScripts/AppCreationScripts.md, AppCreationScripts/Cleanup.ps1, AppCreationScripts/Configure.ps1, AppCreationScripts/Steps.md, iwa-console.sln, iwa-console/iwa-console.csproj, iwa-console/packages.config
Improving the readme.md
updating to the latest MSAL.NET
* ...
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
[x ] Documentation content changes
```
```
cd [repo-name]
```
```
Follow the README.md (including the automated scripts)
```
=> Adding app creation scripts

iwa-console/MyInformation.cs
Aligning this sample with the U/P sample
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Aligning this sample with the U/P sample

iwa-console/AuthenticationConfig.cs, iwa-console/Program.cs, iwa-console/iwa-console.csproj
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Update to MSAL.NET 3.0.3-preview

iwa-console/iwa-console.csproj
=> Update to MSAL.NET 4.0

iwa-console/iwa-console.csproj
=> update to msal420

README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix typos in README.MD

README.md
* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> YAML updates for samples browser

iwa-console/iwa-console.csproj
=> Update to 4.13

iwa-console/iwa-console.csproj
Update to MSAL.NET 4.18
```
[ ] Yes
[ x ] No
```
=> Update to MSAL.NET 4.18

iwa-console/MyInformation.cs, iwa-console/iwa-console.csproj
=> Update to MSAL.NET 4.20

iwa-console/AuthenticationConfig.cs, iwa-console/MyInformation.cs, iwa-console/PublicAppUsingIntegratedWindowsAuthentication.cs
* typography changes
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
=> fix typography

iwa-console/iwa-console.csproj
Update to MSAL 4.25.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Dependency Update
```
tested
=> Updating MSAL to 4.25.0

iwa-console/iwa-console.csproj
Update to MSAL 4.26.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Dependency Update
```
Tested
=> Update MSAL to 4.26.0

iwa-console/iwa-console.csproj
Upgraded to nuget pkg 4.32
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Upgrade
```
*  Run the sample
```
cd [repo-name]
npm install
```
```
Manual run
```
* Acquires token
=> Upgraded to 4.32

iwa-console/iwa-console.csproj
Update to MSAL 4.34.0
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update to MSAL 4.34.0
```
Tested manually
=> Update to MSAL 4.34.0

iwa-console/iwa-console.csproj
Update to MSAL 4.35.0
```
[ ] Yes
[x] No
```
Update to MSAL 4.35.0
Manually tested
=> Update to MSAL 4.35.0

iwa-console/iwa-console.csproj
Update to MSAL 4.36.0
Manually tested
=> Update to MSAL 4.36.0

iwa-console/iwa-console.csproj
Updating to the latest MSAL 438.0
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
Get the code
=> Updating to MSAL 4.38.0

iwa-console/iwa-console.csproj
Updated to MSAL .Net 4.40
[ ] Yes
[x] No
```
[ ] Bugfix
[ ] Feature
[x] Other... Sample Update
```
=> Updated to MSAL .Net 4.40

iwa-console/iwa-console.csproj
Updated to msal 4.41.0
[  ] Yes
[X] No
[ ] Bugfix
[ ] Feature
[x] Other... sample update
=> Updated to msal 4.41.0

iwa-console/iwa-console.csproj
Update to MSAL 4.42.0
[ ] Yes
[x] No
`
[ ] Bugfix
[ ] Feature
[x] Other... Update to MSAL 4.42.0
=> Update to MSAL 4.42.0

iwa-console/iwa-console.csproj
Update to MSAL 4.43.0
[ ] Yes
[X] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update to MSAL 4.43.0
=> Update to MSAL 4.43.0

iwa-console/iwa-console.csproj
Update to MSAL 4.44.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update to MSAL 4.44.0
=> Update to MSAL 4.44.0

iwa-console/iwa-console.csproj
Update to MSAL 4.46.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Update to MSAL 4.46.0
=> Update to MSAL 4.46.0

iwa-console/iwa-console.csproj
=> Update to MSAL 4.47.0

iwa-console/iwa-console.csproj
Update to MSAL 4.48.0
[ ] Yes
[x ] No
[ ] Bugfix
[ ] Feature
[ ] Other... Please describe: Update to MSAL 4.48.0
=> Update to MSAL 4.48.0

iwa-console/iwa-console.csproj
=> Update to MSAL 4.49.0

iwa-console/iwa-console.csproj
Update to MSAL 4.50.0
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update to MSAL 4.50.0
=> Update to MSAL 4.50.0

iwa-console/MyInformation.cs, iwa-console/Program.cs, iwa-console/ProtectedApiCallHelper.cs, iwa-console/PublicAppUsingIntegratedWindowsAuthentication.cs, iwa-console/iwa-console.csproj
=> Update to use MSAL 4.51.0

iwa-console/iwa-console.csproj
=> Update to MSAL 4.52.0

iwa-console/iwa-console.csproj
=> Update to use MSAL 4.54.0
